config/routes.rb
Rails.application.routes.draw do

  root to: 'orden_trabajos#index'
  resources :orden_trabajos

  resources :orden_trabajos_imports, only: [:new, :create]
  get 'orden_trabajos_imports/new'
  get 'orden_trabajos_imports/create'


# Rutas creadas para cada pantalla
    get 'listado', to: 'orden_trabajos#listado', as: :listado
    get 'offset', to: 'orden_trabajos#offset', as: :offset
    get 'digital', to: 'orden_trabajos#digital', as: :digital
    get 'post1', to: 'orden_trabajos#post1', as: :post1
    get 'post2', to: 'orden_trabajos#post2', as: :post2
    get 'post3', to: 'orden_trabajos#post3', as: :post3
    get 'post4', to: 'orden_trabajos#post4', as: :post4
    get 'post5', to: 'orden_trabajos#post5', as: :post5
    get 'post6', to: 'orden_trabajos#post6', as: :post6
    get 'post7', to: 'orden_trabajos#post7', as: :post7

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
    
    post 'update_checklist' => 'checklists#update_checklist'

end

app/models/orden_trabajo.rb
class OrdenTrabajo < ApplicationRecord
	POST = { "1" => "Ko", "2" => "SM", "3" => "PM", "4" => "GTO", "5" => "Xe", "6" => "Buv", "7" => "Lam", "8" => "Minerva", "9" => "Plana", "10" => "Fidia", "11" => "Baum", "12" =>"Renz","13" => "Duplo", "14" =>"C.Hilo", "15" => "Binder", "16" => "Zechini", "17" => "Alzadora", "18" => "C.Alambre", "19" => "Guillotina", "20" => "T.Manual", "21" => "Otros", "22" => "Empaque"}

	MAQUINA = ["Ko", "SM", "PM", "GTO","Xe"]
end

app/controllers/orden_trabajos_controller.rb
class OrdenTrabajosController < ApplicationController

  before_action :set_orden_trabajo, only: [:show, :edit, :update, :destroy]  
  before_action :listado_trabajo, only:[:digital, :offset, :post1, :post2, :post3, :post4, :post5, :post6, :post7]


  # GET /orden_trabajos
  # GET /orden_trabajos.json
  def index
    @orden_trabajos = OrdenTrabajo.all.order('clinom ASC')
    respond_to do |format|
      format.html # index.html.erb
      format.js # index.js.erb
      format.json { render json: @orden_trabajos}
             format.pdf do
        render pdf: 'listado/pdf', pdf: 'Listado'
      end
    end
  end

  def listado
    @orden_trabajos = OrdenTrabajo.all.order('clinom ASC')
    respond_to do |format|
      format.html # index.html.erb
      format.js # index.js.erb
      format.json { render json: @orden_trabajos}

      format.xlsx {
        response.headers[
          'Content-Disposition'
        ] = "attachment; filename = Listado_ordenes_trabajo.xlsx"
      }

      format.pdf do
        render pdf: 'listado/pdf', pdf: 'Listado',
        :orientation => 'landscape'
      end

    end
  end

  # GET /orden_trabajos/1
  # GET /orden_trabajos/1.json
  def show
  end
  # GET /orden_trabajos/new
  def new
    @orden_trabajo = OrdenTrabajo.new
  end

  # GET /orden_trabajos/1/edit
  def edit
    respond_to do |format|
      format.html # index.html.erb
      format.js
    end
  end

  # POST /orden_trabajos
  # POST /orden_trabajos.json
  def create
    @orden_trabajo = OrdenTrabajo.new(orden_trabajo_params)

    respond_to do |format|
      if @orden_trabajo.save
        format.html { redirect_to @orden_trabajo, notice: 'Orden trabajo was successfully created.' }
        format.json { render :show, status: :created, location: @orden_trabajo }
      else
        format.html { render :new }
        format.json { render json: @orden_trabajo.errors, status: :unprocessable_entity }
      end
    end
  end


  # PATCH/PUT /orden_trabajos/1
  # PATCH/PUT /orden_trabajos/1.json
  def update
    respond_to do |format|
      if @orden_trabajo.update(orden_trabajo_params)
        format.html { redirect_to @orden_trabajo, notice: 'Orden trabajo was successfully updated.' }
        format.json { render :show, status: :ok, location: @orden_trabajo }
        format.js
      else
        format.html { render :edit }
        format.json { render json: @orden_trabajo.errors, status: :unprocessable_entity }
      end
    end
  end


  # DELETE /orden_trabajos/1
  # DELETE /orden_trabajos/1.json
  def destroy
    @orden_trabajo.destroy
    respond_to do |format|
      format.html { redirect_to orden_trabajos_url, notice: 'Orden trabajo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


# ESTE SECTOR DEL CONTROLADOR ES PARA LAS DIFERENTES VIEWS DE IMPRESIÓN Y POST
# ------------------------------------------------------------------------
def digital
   @orden_trabajos = OrdenTrabajo.all.order('fecentr ASC')
end

def offset
   @orden_trabajos = OrdenTrabajo.all.order('fecentr ASC')
end

def post1
   @orden_trabajos = OrdenTrabajo.all.order('fecentr ASC')
end

def post2
   @orden_trabajos = OrdenTrabajo.all.order('fecentr ASC')
end

def post3
   @orden_trabajos = OrdenTrabajo.all.order('fecentr ASC')
end

def post4
   @orden_trabajos = OrdenTrabajo.all.order('fecentr ASC')
end

def post5
   @orden_trabajos = OrdenTrabajo.all.order('fecentr ASC')
end

def post6
   @orden_trabajos = OrdenTrabajo.all.order('fecentr ASC')
end

def post7
   @orden_trabajos = OrdenTrabajo.all.order('fecentr ASC')
end

# ------------------------------------------------------------------------

  private
    # Use callbacks to share common setup or constraints between actions.

    def listado_trabajo
      @orden_trabajos = OrdenTrabajo.all.order('fecentr ASC')
    end


    def set_orden_trabajo
      @orden_trabajo = OrdenTrabajo.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def orden_trabajo_params
      params.require(:orden_trabajo).permit(:trnum, :clinom, :nomprod,  :fecentr, :procesos, :observaciones, :estado_actual, :estado)
    end
end

app/helpers/orden_trabajos_helper.rb
module OrdenTrabajosHelper

    def cadenatovector(cadena)
        if cadena == nil
      return [""]
        else
            cadena = cadena.gsub "[", ""
            cadena = cadena.gsub "]", ""
            cadena = cadena.gsub '"', ""
            cadena = cadena.gsub "'", ""
            cadena = cadena.gsub " ", ""
            return cadena.split(",")
        end
    end

    def cadenatohash(cadena)
        
        hash_post = Hash.new
        OrdenTrabajo::POST.each do |clave, valor|
            if cadenatovector(cadena).include? valor
                hash_post[clave] = valor
            end
        end
        return hash_post
    end


    def options_for_select(container, selected = nil)
        return container if String === container

        selected, disabled = extract_selected_and_disabled(selected).map do |r|
          Array(r).map(&:to_s)
        end

        container.map do |element|
          html_attributes = option_html_attributes(element)
          text, value = option_text_and_value(element).map(&:to_s)

          html_attributes[:selected] ||= option_value_selected?(value, selected)
          html_attributes[:disabled] ||= disabled && option_value_selected?(value, disabled)
          html_attributes[:value] = value

          tag_builder.content_tag_string(:option, text, html_attributes)
        end.join("\n").html_safe
    end
    
end

app/views/orden_trabajos/_form.html.erb
<div class="container">
<h3 class="font-weight-bold text-center"> <%= orden_trabajo.clinom %> </h3>
<%= simple_form_for (@orden_trabajo)  do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
  <div class="select1">
    <%= f.input :nomprod, label: "Producto"%>
    <%= f.input :observaciones %>

  <div class="d-flex justify-content-between w-75 mt-5">
    <div class="mr-5 "><%= f.input :trcan,label: "Cantidad"%></div>
    <div class="mr-5"><%= f.input :fecentr, :class => 'datepicker', :default=>Date.today + 15.day, as: :date, html5: true ,label: "Fecha Entrega" %></div>

    <div class="">
      <p class="font-weight-bold text-center">Proceso</p>
      <!-- Multiselect dropdown orden_trabajo.procesos -->
      <script type="text/javascript">
        $(document).ready(function() {
          $("#orden_trabajo_procesos_<%=orden_trabajo.id%>").multiselect({
            allSelectedText: 'Showing All'
          });
        });
      //Fin del efecto multiselect orden_trabajo.procesos

      //Cambia los valores de la cadena de proceso
      $(function () {

        $("#orden_trabajo_procesos_<%=orden_trabajo.id%>").change(function () {
          var ValorSeleccionadoDropdown = $(this).val();
          document.getElementById("MuestraProcesoPost_<%=orden_trabajo.id%>").innerHTML = ValorSeleccionadoDropdown;
          $(document).ready(function(){$("#<%=orden_trabajo.id%>").val(ValorSeleccionadoDropdown)});
        });
      });

      //Fin de cambio los valores de la cadena de proceso
      function almacenar_valores(ValorSeleccionadoDropdown){
        var orden_trabajo_procesosanterior =  document.getElementById("MuestraProcesoPost_<%=orden_trabajo.id%>");
        console.log(orden_trabajo_procesosanterior);
      }

      // Inicio de Date Picekr
      $('.datepicker').datepicker({
        format: 'mm/dd/yyyy',
        startDate: '-3d'
      });
     // Fin del Date Picker
    </script>

    <select id= "orden_trabajo_procesos_<%=orden_trabajo.id%>" multiple="multiple" >
      <% OrdenTrabajo::POST.each do  |clave, valor| %>

                  <%if valor == cadenatohash(orden_trabajo.procesos)[clave] %>
                    <option id=<%clave%> value = <%= cadenatohash(orden_trabajo.procesos)[clave] %> selected><%= cadenatohash(orden_trabajo.procesos)[clave] %></option>
                  <%else%>
                    <option id=<%clave%> value = <%= valor %> ><%= valor %></option>
                  <%end%>
              <%end%>
            </select>

          <%= f.input :procesos, :as => :hidden, :input_html => { :id => orden_trabajo.id} %>
          <p id="MuestraProcesoPost_<%=orden_trabajo.id%>"></p>

    </div>
  </div>
  </div>
<div class="d-flex justify-content-between mt-5">
  <div class="w-25 mr-3"> <%= f.input :trnum, label: "Ot"  %> </div>
  <div class="w-75 ml-3"> <%= f.input :clinom, label: "Nombre" %> </div>
</div>
<div>
  <%= f.button :submit, name="Confirmar", :class => "center-block btn btn-primary btn-lg btn-block w-50  mt-5"%>
</div>
<% end %>

app/views/orden_trabajos/digital.html.erb
<div class="d-flex justify-content-around">
  <div class="container">
      <table class="table table-striped">
        <h1 class="mt-3">Konica Color</h1>
      <thead>
        <tr>
          <th>Cliente</th>
          <th>Producto</th>
          <th>Observación</th>
          <th>Fecha Entrega</th>
        </tr>
      </thead>
      <tbody>
    <% @orden_trabajos.each do |orden_trabajo| %>
    <% if orden_trabajo.post.include? "Ko" %>
          <tr class="<%= "bg-danger font-weight-bold" if (orden_trabajo.fecha_entrega <= Date.today + 1) %>">
            <td><%= orden_trabajo.cliente %></td>
            <td><%= orden_trabajo.producto %></td>
            <td><%= truncate(orden_trabajo.observaciones, :length => 50)%></td>
            <td><%= orden_trabajo.fecha_entrega %></td>
            <td>
        <% end %>
      <% end %>
        </tr>
      </tbody>
    </table>
  </div>
    <div class="container">
      <table class="table table-striped">
        <h1 class="mt-3">Konica Monocolor</h1>
      <thead>
        <tr>
          <th>Cliente</th>
          <th>Producto</th>
          <th>Observación</th>
          <th>Fecha Entrega</th>
        </tr>
      </thead>
      <tbody>
    <% @orden_trabajos.each do |orden_trabajo| %>
    <% if orden_trabajo.post.include? "Xe" %>

          <tr class="<%= "bg-danger font-weight-bold" if (orden_trabajo.fecha_entrega <= Date.today + 1) %>">
            <td><%= orden_trabajo.cliente %></td>
            <td><%= orden_trabajo.producto %></td>
            <td><%= truncate(orden_trabajo.observaciones, :length => 50)%></td>
            <td> <%= orden_trabajo.fecha_entrega %></td>
          <% end %>
        <% end %>
        </tr>
      </tbody>
    </table>
  </div>
</div>


<script>
//Using setTimeout to execute a function after 5 seconds.
setTimeout(function () {
   //Redirect with JavaScript
   window.location.href= 'http://localhost:3000/offset';
},  5000);

</script>

app/views/orden_trabajos/edit.html.erb
<h4 class="text-center">Editar Orden de Trabajo</h4>


<%= render 'form', orden_trabajo: @orden_trabajo %>

<%= link_to 'Atrás', orden_trabajos_path, {:class => "center-block btn btn-dark btn-lg btn-block w-50 mt-5"} %>

app/views/orden_trabajos/index.html.erb
<p id="notice"><%= notice %></p>
<div class="d-flex justify-content-between mr-5 ml-2">
  <div class="ml-3 mb-2"><h3>Planilla de control</h3></div>
  <div><h3><%= link_to ' + Nuevo trabajo', new_orden_trabajo_path %></h3></div>
</div>
<script>
  $(document).ready(function(){
  $("#buscador_datos").on("keyup", function() {
    var value = $(this).val().toLowerCase();
    $("#TablaOrdenesTrabajos tr").filter(function() {
      $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
    });
    console.log(value);
  });
});
</script>
<input class="ml-3 w-25" id="buscador_datos" type="text" placeholder="Buscar trabajo">

<table class="table table-striped  m-2">
  <thead>
    <tr>
      <th>Ot</th>
      <th>Cliente</th>
      <th>Producto</th>
      <th>Estado actual</th>
      <th>Proceso</th>
      
      <th>Fecha entrega</th>
      <th>Observaciones</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <!--Incio Tabla-->
  <tbody id="TablaOrdenesTrabajos">
    <% @orden_trabajos.each do |orden_trabajo| %>
      <%= simple_form_for (orden_trabajo) do |f| %>
      
        <tr>
          <td><%= link_to orden_trabajo.trnum, orden_trabajo %></td>
          <td><%= link_to orden_trabajo.clinom, orden_trabajo %></td>
          <td><%= link_to orden_trabajo.nomprod, orden_trabajo %></td>
          <td>
            <%= f.input :estado_actual, as: :select, :collection => ["Pendiente", "Diseño Diego", "Diseño Ismael", "Diseño Eduardo", "Diseño Miguel", "Diseño Santiago", "CTP", "Impresión", "Procesos", "Terminado"], label: false, :default=> "Pendiente" %>              
          </td>
          <td>
            <script>
              // Multiselect dropdown orden_trabajo.post -->
              $(document).ready(function() {
                $("#orden_trabajo_procesos_<%=orden_trabajo.id%>").multiselect({
                    allSelectedText: 'Showing All'
                });
              });
              //Fin del efecto multiselect orden_trabajo.post

              //Cambia los valores de la cadena de proceso
              $(function () {
                $("#orden_trabajo_procesos_<%=orden_trabajo.id%>").change(function () {
                  var ValorSeleccionadoDropdown = $(this).val();
                  $(document).ready(function(){$("#<%=orden_trabajo.id%>").val(ValorSeleccionadoDropdown)});  
                  
                });
              });
              //Fin de cambio los valores de la cadena de proceso

              // Inicio de Date Picekr
              $('.datepicker').datepicker({format: 'mm/dd/yyyy',startDate: '-3d'});
              // Fin del Date Picker

            </script>
            
            <!-- Multiselect dropdown html -->
            <select id= "orden_trabajo_procesos_<%=orden_trabajo.id%>" multiple="multiple">
              <% OrdenTrabajo::POST.each do  |clave, valor| %>
                  <%if valor == cadenatohash(orden_trabajo.procesos)[clave] %>
                    <option value = <%= cadenatohash(orden_trabajo.procesos)[clave] %> selected><%= cadenatohash(orden_trabajo.procesos)[clave] %>
                    </option>
                  <%else%>
                    <option value = <%=valor%> ><%= valor %></option>
                  <%end%>
              <%end%>
            </select>
            <!-- Fin multiselect dropdown html -->
          </td>  

          <td><%= f.input :procesos, :as => :hidden, :input_html => { :id => orden_trabajo.id} %></td>
          <td><%= f.input :fecentr, :class => 'datepicker', :default=>Date.today + 15.day, as: :date, html5: true ,label: false %></td>
          <td><%= f.input :observaciones,  label: false %></td>

           <td><%= button_to :submit, name="OK", :class => "btn btn-primary btn-lg"%></td>
          <td><%= button_to 'Eliminar', orden_trabajo, method: :delete, data: { confirm: '¿Estás seguro/a?' } %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
  <!--Fin Tabla-->
</table>

app/views/orden_trabajos/listado.html.erb
<p id="notice"><%= notice %></p>
<div class="d-flex justify-content-between mr-5 ml-2">
  <div class="ml-3 mb-2"><h3>Listados de trabajos en el taller</h3></div>
  <div><h3><%= link_to 'Descargar pdf', listado_path(format: 'pdf')  %></h3></div>
  <div><h3><%= link_to 'Descargar Excel', listado_path(format: 'xlsx')  %></h3></div>
  <div><h3><%= link_to 'Importar Excel', orden_trabajos_imports_new_path %></h3></div>



</div>

<!--Buscador Jquery-->
<script>
  $(document).ready(function(){
  $("#buscador_datos").on("keyup", function() {
    var value = $(this).val().toLowerCase();
    $("#TablaOrdenesTrabajos tr").filter(function() {
      $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
    });
  });
});
</script>
<input class="ml-3 w-25" id="buscador_datos" type="text" placeholder="Buscar trabajo">
<!--Fin buscador jquery-->


<table class="table table-striped  m-2">
  <thead>
    <tr>
      <th>Ot</th>
      <th>Cliente</th>
      <th>Producto</th>
      <th>Procesos</th>
      <th>Fecha entrega</th>
      <th>Observaciones</th>
      <th colspan="3"></th>
    </tr>
  </thead>

<!--Incio Tabla-->
  <tbody id="TablaOrdenesTrabajos">
    <% @orden_trabajos.each do |orden_trabajo| %>
      <tr>
        <td><%= link_to orden_trabajo.trnum, orden_trabajo %></td>
        <td><%= link_to orden_trabajo.clinom, orden_trabajo %></td>
        <td><%= link_to orden_trabajo.nomprod, orden_trabajo %></td>
        <td><%= orden_trabajo.procesos %></td>
        <td><%= orden_trabajo.fecentr%></td>
        <td><%= truncate(orden_trabajo.observaciones, :length => 50)%></td>
      </tr>
    <% end %>
  </tbody>
  <!--Fin Tabla-->
</table>

app/views/orden_trabajos/offset.html.erb
<div class="d-flex justify-content-between">


  <div class="container">
      <table class="table table-striped">
        <h1 class="mt-3">SM</h1>
      <thead>
        <tr>
          <th>Cliente</th>
          <th>Producto</th>
          <th>Observación</th>
          <th>Fecha Entrega</th>
        </tr>
      </thead>
      <tbody>
    <% @orden_trabajos.each do |orden_trabajo| %>
    <% if orden_trabajo.post.include? "SM" %>
          <tr class="<%= "bg-danger font-weight-bold" if (orden_trabajo.fecha_entrega <= Date.today + 1) %>">
            <td><%= orden_trabajo.cliente %></td>
            <td><%= orden_trabajo.producto %></td>
            <td><%= truncate(orden_trabajo.observaciones, :length => 50)%></td>
            <td><%= orden_trabajo.fecha_entrega %></td>
            <td>
        <% end %>
      <% end %>
        </tr>
      </tbody>
    </table>
  </div>

    <div class="container">
      <table class="table table-striped">
        <h1 class="mt-3">PM</h1>
      <thead>
        <tr>
          <th>Cliente</th>
          <th>Producto</th>
          <th>Observación</th>
          <th>Fecha Entrega</th>
        </tr>
      </thead>
      <tbody>
    <% @orden_trabajos.each do |orden_trabajo| %>
    <% if orden_trabajo.post.include? "PM" %>

          <tr class="<%= "bg-danger font-weight-bold" if (orden_trabajo.fecha_entrega <= Date.today + 1) %>">
            <td><%= orden_trabajo.cliente %></td>
            <td><%= orden_trabajo.producto %></td>
            <td><%= truncate(orden_trabajo.observaciones, :length => 50)%></td>
            <td> <%= orden_trabajo.fecha_entrega %></td>
          <% end %>
        <% end %>
        </tr>
      </tbody>
    </table>
  </div>


 <div class="container">
      <table class="table table-striped">
        <h1 class="mt-3">GTO</h1>
      <thead>
        <tr>
          <th>Cliente</th>
          <th>Producto</th>
          <th>Observación</th>
          <th>Fecha Entrega</th>
        </tr>
      </thead>
      <tbody>
    <% @orden_trabajos.each do |orden_trabajo| %>
    <% if orden_trabajo.post.include? "GTO" %>

          <tr class="<%= "bg-danger font-weight-bold" if (orden_trabajo.fecha_entrega <= Date.today + 1) %>">
            <td><%= orden_trabajo.cliente %></td>
            <td><%= orden_trabajo.producto %></td>
            <td><%= truncate(orden_trabajo.observaciones, :length => 50)%></td>
            <td> <%= orden_trabajo.fecha_entrega %></td>
          <% end %>
        <% end %>
        </tr>
      </tbody>
    </table>
  </div>
</div>

</div>

<script>
//Using setTimeout to execute a function after 5 seconds.
setTimeout(function () {
   //Redirect with JavaScript
   window.location.href= 'http://localhost:3000/digital';
},  5000);
</script>

app/views/orden_trabajos/post1.html.erb
<div class="d-flex justify-content-around">
  <div class="container">
      <table class="table table-striped">
        <h1 class="mt-3">Buv</h1>
      <thead>
        <tr>
          <th>Cliente</th>
          <th>Producto</th>
          <th>Observación</th>
          <th>Fecha Entrega</th>
        </tr>
      </thead>
      <tbody>
    <% @orden_trabajos.each do |orden_trabajo| %>
    <% if orden_trabajo.post.include? "Buv" %>
          <tr class="<%= "bg-danger font-weight-bold" if (orden_trabajo.fecha_entrega <= Date.today + 1) %>">
            <td><%= orden_trabajo.cliente %></td>
            <td><%= orden_trabajo.producto %></td>
            <td><%= truncate(orden_trabajo.observaciones, :length => 50)%></td>
            <td><%= orden_trabajo.fecha_entrega %></td>
            <td>
        <% end %>
      <% end %>
        </tr>
      </tbody>
    </table>
  </div>
    <div class="container">
      <table class="table table-striped">
        <h1 class="mt-3">Laminado</h1>
      <thead>
        <tr>
          <th>Cliente</th>
          <th>Producto</th>
          <th>Observación</th>
          <th>Fecha Entrega</th>
        </tr>
      </thead>
      <tbody>
    <% @orden_trabajos.each do |orden_trabajo| %>
    <% if orden_trabajo.post.include? "Lam" %>

          <tr class="<%= "bg-danger font-weight-bold" if (orden_trabajo.fecha_entrega <= Date.today + 1) %>">
            <td><%= orden_trabajo.cliente %></td>
            <td><%= orden_trabajo.producto %></td>
            <td><%= truncate(orden_trabajo.observaciones, :length => 50)%></td>
            <td> <%= orden_trabajo.fecha_entrega %></td>
          <% end %>
        <% end %>
        </tr>
      </tbody>
    </table>
  </div>
</div>


<!--
//Using setTimeout to execute a function after 5 seconds.
setTimeout(function () {
   //Redirect with JavaScript
   window.location.href= 'http://localhost:3000/offset';
},  30000);
 -->

app/views/orden_trabajos/post2.html.erb
<div class="d-flex justify-content-around">
  <div class="container">
      <table class="table table-striped">
        <h1 class="mt-3">Plana</h1>
      <thead>
        <tr>
          <th>Cliente</th>
          <th>Producto</th>
          <th>Observación</th>
          <th>Fecha Entrega</th>
        </tr>
      </thead>
      <tbody>
    <% @orden_trabajos.each do |orden_trabajo| %>
    <% if orden_trabajo.post.include? "Plana" %>
          <tr class="<%= "bg-danger font-weight-bold" if (orden_trabajo.fecha_entrega <= Date.today + 1) %>">
            <td><%= orden_trabajo.cliente %></td>
            <td><%= orden_trabajo.producto %></td>
            <td><%= truncate(orden_trabajo.observaciones, :length => 50)%></td>
            <td><%= orden_trabajo.fecha_entrega %></td>
            <td>
        <% end %>
      <% end %>
        </tr>
      </tbody>
    </table>
  </div>
    <div class="container">
      <table class="table table-striped">
        <h1 class="mt-3">Minerva</h1>
      <thead>
        <tr>
          <th>Cliente</th>
          <th>Producto</th>
          <th>Observación</th>
          <th>Fecha Entrega</th>
        </tr>
      </thead>
      <tbody>
    <% @orden_trabajos.each do |orden_trabajo| %>
    <% if orden_trabajo.post.include? "Minerva" %>

          <tr class="<%= "bg-danger font-weight-bold" if (orden_trabajo.fecha_entrega <= Date.today + 1) %>">
            <td><%= orden_trabajo.cliente %></td>
            <td><%= orden_trabajo.producto %></td>
            <td><%= truncate(orden_trabajo.observaciones, :length => 50)%></td>
            <td> <%= orden_trabajo.fecha_entrega %></td>
          <% end %>
        <% end %>
        </tr>
      </tbody>
    </table>
  </div>
</div>


<!--
//Using setTimeout to execute a function after 5 seconds.
setTimeout(function () {
   //Redirect with JavaScript
   window.location.href= 'http://localhost:3000/offset';
},  30000);
 -->

app/views/orden_trabajos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Ot:</strong>
  <%= @orden_trabajo.trnum %>
</p>


<p>
  <strong>Cliente:</strong>
  <%= @orden_trabajo.clinom %>
</p>

<p>
  <strong>Producto:</strong>
  <%= @orden_trabajo.nomprod %>
</p>

<p>
  <strong>Procesos:</strong>
  <%= @orden_trabajo.procesos %>
</p>
<p>
  <strong>Fecha de Entrega:</strong>
  <%= @orden_trabajo.fecentr %>
</p>
<p>
  <strong>Observaciones:</strong>
  <%= @orden_trabajo.observaciones %>
</p>
<p>
  <strong>Estado Actual:</strong>
  <%= @orden_trabajo.estado_actual %>
</p>

<%= link_to 'Edit', edit_orden_trabajo_path(@orden_trabajo) %> |
<%= link_to 'Back', orden_trabajos_path %>